{{- if .Values.serviceAccount.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cloudquery
spec:
  provider: aws
  secretObjects:
  - secretName: cloudquery-sm
    type: Opaque
    data: 
    - objectName: {{ include "cloudquery.fullname" . }}
      key: CQ_VAR_DSN
  parameters:
    objects: |
        - objectName: "{{ include "cloudquery.fullname" . }}"
          objectType: "secretsmanager"
{{- end }}